export const baseClassName = 'hub-select'
export const dropClassName = 'select-drop'
export const itemClassName = 'select-item'
export const disabledClassName = 'is-disabled'
export const selectedClassName = 'is-selected'
export const iconClassName = 'select-icon'
export const iconCommonClassName = 'hub-icon'
